import { describe, it, expect } from "vite-plus/test";
import { generate, generateTypes } from "../src/generate.js";
import { parseHelpText } from "../src/parse-help-text.js";
import type { ParsedFlag } from "../src/parse-help-text.js";

const SAMPLE_HELP = `Usage: my-tool [options] [command]

A sample tool.

Options:
  -v, --verbose     Be verbose
  -o, --output <file>  Output file

Commands:
  build              Build the project
  serve              Start dev server
`;

const createFlagsForSubcommand = (): ParsedFlag[] => [
  {
    longName: "watch",
    shortName: "-w",
    description: "Watch for changes",
    takesValue: false,
    valueName: null,
    defaultValue: null,
    isNegated: false,
  },
  {
    longName: "output-dir",
    shortName: "-o",
    description: "Output directory",
    takesValue: true,
    valueName: "dir",
    defaultValue: null,
    isNegated: false,
  },
  {
    longName: "dry-run",
    shortName: null,
    description: "Show what would happen",
    takesValue: false,
    valueName: null,
    defaultValue: null,
    isNegated: false,
  },
];

describe("generate", () => {
  it("generates valid TypeScript by default", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const code = generate(schema);

    expect(code).toContain("interface CommandResult");
    expect(code).toContain('const BINARY = "my-tool"');
    expect(code).toContain("export const build");
    expect(code).toContain("export const serve");
    expect(code).toContain("export const myTool");
    expect(code).toContain("export default myTool");
  });

  it("generates JavaScript when typescript is false", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const code = generate(schema, { typescript: false });

    expect(code).not.toContain("interface CommandResult");
    expect(code).not.toContain(": Record<string, unknown>");
    expect(code).toContain("export const build");
    expect(code).toContain("export default myTool");
  });

  it("includes header comment", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const code = generate(schema);

    expect(code).toContain("Generated by cli-to-js");
  });

  it("generates subcommand exports from schema", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const code = generate(schema);

    expect(code).toContain('run(["build"], options)');
    expect(code).toContain('run(["serve"], options)');
  });

  it("includes subcommand descriptions in JSDoc", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const code = generate(schema);

    expect(code).toContain("Build the project");
    expect(code).toContain("Start dev server");
  });

  it("converts kebab-case binary names to valid identifiers", () => {
    const schema = parseHelpText("my-cool-tool", "Usage: my-cool-tool [options]");
    const code = generate(schema);

    expect(code).toContain("export const myCoolTool");
    expect(code).toContain("export default myCoolTool");
  });

  it("generates a root command export", () => {
    const schema = parseHelpText("docker", SAMPLE_HELP);
    const code = generate(schema);

    expect(code).toContain("export const docker");
    expect(code).toContain("run([], options)");
  });

  it("generates working code for a tool with no subcommands", () => {
    const schema = parseHelpText("echo", "Usage: echo [options]");
    const code = generate(schema);

    expect(code).toContain("export const echo");
    expect(code).toContain("export default echo");
    expect(code).not.toContain("export const undefined");
  });

  it("embeds the spawn runtime inline", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const code = generate(schema);

    expect(code).toContain('import { spawn } from "node:child_process"');
    expect(code).toContain("const toArgs");
    expect(code).toContain("const run");
  });

  describe("typed interfaces", () => {
    it("generates an options interface for subcommands with flags", () => {
      const schema = parseHelpText("my-tool", SAMPLE_HELP);
      schema.command.subcommands.find((subcmd) => subcmd.name === "build")!.flags =
        createFlagsForSubcommand();

      const code = generate(schema);

      expect(code).toContain("interface BuildOptions {");
      expect(code).toContain("watch?: boolean;");
      expect(code).toContain("outputDir?: string;");
      expect(code).toContain("dryRun?: boolean;");
      expect(code).toContain("_?: string | string[];");
      expect(code).toContain("[key: string]: unknown;");
    });

    it("uses the typed interface as the parameter type", () => {
      const schema = parseHelpText("my-tool", SAMPLE_HELP);
      schema.command.subcommands.find((subcmd) => subcmd.name === "build")!.flags =
        createFlagsForSubcommand();

      const code = generate(schema);

      expect(code).toContain("(options: BuildOptions = {})");
    });

    it("converts kebab-case flag names to camelCase properties", () => {
      const schema = parseHelpText("my-tool", SAMPLE_HELP);
      schema.command.subcommands.find((subcmd) => subcmd.name === "build")!.flags =
        createFlagsForSubcommand();

      const code = generate(schema);

      expect(code).toContain("outputDir?: string;");
      expect(code).toContain("dryRun?: boolean;");
      expect(code).not.toContain("output-dir?:");
      expect(code).not.toContain("dry-run?:");
    });

    it("maps value flags to string and boolean flags to boolean", () => {
      const schema = parseHelpText("my-tool", SAMPLE_HELP);
      schema.command.subcommands.find((subcmd) => subcmd.name === "build")!.flags =
        createFlagsForSubcommand();

      const code = generate(schema);

      expect(code).toContain("watch?: boolean;");
      expect(code).toContain("outputDir?: string;");
    });

    it("includes JSDoc for flag descriptions in the interface", () => {
      const schema = parseHelpText("my-tool", SAMPLE_HELP);
      schema.command.subcommands.find((subcmd) => subcmd.name === "build")!.flags =
        createFlagsForSubcommand();

      const code = generate(schema);

      expect(code).toContain("/** Watch for changes */");
      expect(code).toContain("/** Output directory */");
      expect(code).toContain("/** Show what would happen */");
    });

    it("does not duplicate flag docs in function JSDoc when interface exists", () => {
      const schema = parseHelpText("my-tool", SAMPLE_HELP);
      schema.command.subcommands.find((subcmd) => subcmd.name === "build")!.flags =
        createFlagsForSubcommand();

      const code = generate(schema);

      const buildJsdocStart = code.indexOf("/** my-tool build");
      const buildExportStart = code.indexOf("export const build");
      const jsdocBlock = code.slice(buildJsdocStart, buildExportStart);
      expect(jsdocBlock).not.toContain("@param");
    });

    it("falls back to Record<string, unknown> for subcommands without flags", () => {
      const schema = parseHelpText("my-tool", SAMPLE_HELP);
      schema.command.subcommands.find((subcmd) => subcmd.name === "build")!.flags =
        createFlagsForSubcommand();

      const code = generate(schema);

      expect(code).toContain("interface BuildOptions");
      expect(code).not.toContain("interface ServeOptions");

      const serveExportStart = code.indexOf("export const serve");
      const serveSignature = code.slice(serveExportStart, serveExportStart + 80);
      expect(serveSignature).toContain("Record<string, unknown>");
    });

    it("generates a typed interface for the root command when it has flags", () => {
      const schema = parseHelpText("my-tool", SAMPLE_HELP);

      const code = generate(schema);

      expect(code).toContain("interface MyToolOptions {");
      expect(code).toContain("verbose?: boolean;");
      expect(code).toContain("output?: string;");
      expect(code).toContain("(options: MyToolOptions = {})");
    });

    it("does not generate interfaces in JS mode", () => {
      const schema = parseHelpText("my-tool", SAMPLE_HELP);
      schema.command.subcommands.find((subcmd) => subcmd.name === "build")!.flags =
        createFlagsForSubcommand();

      const code = generate(schema, { typescript: false });

      expect(code).not.toContain("interface BuildOptions");
      expect(code).not.toContain("interface MyToolOptions");
    });

    it("generates PascalCase interface names from kebab-case subcommands", () => {
      const schema = parseHelpText(
        "my-tool",
        "Usage: my-tool [command]\n\nCommands:\n  dry-run  Test it\n",
      );
      schema.command.subcommands[0].flags = createFlagsForSubcommand();

      const code = generate(schema);

      expect(code).toContain("interface DryRunOptions {");
    });
  });
});

describe("generateTypes", () => {
  it("generates a .d.ts with import from cli-to-js", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const dts = generateTypes(schema);

    expect(dts).toContain(
      'import type { CommandResult, RunConfig, CliSchema, CommandProcess, ParsedCommand } from "cli-to-js"',
    );
  });

  it("generates the API interface named after the binary", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const dts = generateTypes(schema);

    expect(dts).toContain("export interface MyToolApi {");
  });

  it("includes callable overloads for root command", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const dts = generateTypes(schema);

    expect(dts).toContain(
      "(subcommand: string, options?: Record<string, unknown>, config?: RunConfig): Promise<CommandResult>;",
    );
  });

  it("includes subcommand methods on the API interface", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const dts = generateTypes(schema);

    expect(dts).toContain(
      "build(options?: Record<string, unknown>, config?: RunConfig): Promise<CommandResult>;",
    );
    expect(dts).toContain(
      "serve(options?: Record<string, unknown>, config?: RunConfig): Promise<CommandResult>;",
    );
  });

  it("generates typed option interfaces when subcommands have flags", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    schema.command.subcommands.find((subcmd) => subcmd.name === "build")!.flags =
      createFlagsForSubcommand();

    const dts = generateTypes(schema);

    expect(dts).toContain("export interface BuildOptions {");
    expect(dts).toContain("watch?: boolean;");
    expect(dts).toContain("outputDir?: string;");
    expect(dts).toContain(
      "build(options?: BuildOptions, config?: RunConfig): Promise<CommandResult>;",
    );
  });

  it("generates typed root options when root command has flags", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const dts = generateTypes(schema);

    expect(dts).toContain("export interface MyToolOptions {");
    expect(dts).toContain("verbose?: boolean;");
    expect(dts).toContain("output?: string;");
    expect(dts).toContain("(options?: MyToolOptions, config?: RunConfig): Promise<CommandResult>;");
  });

  it("includes $schema, $parse, and $spawn on the API interface", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const dts = generateTypes(schema);

    expect(dts).toContain("$schema: CliSchema;");
    expect(dts).toContain("$parse(subcommandName: string): Promise<ParsedCommand | undefined>;");
    expect(dts).toContain("$parse(): Promise<void>;");
    expect(dts).toContain("$spawn: {");
  });

  it("includes typed spawn methods matching subcommand methods", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    schema.command.subcommands.find((subcmd) => subcmd.name === "build")!.flags =
      createFlagsForSubcommand();

    const dts = generateTypes(schema);

    expect(dts).toContain("build(options?: BuildOptions, config?: RunConfig): CommandProcess;");
    expect(dts).toContain(
      "serve(options?: Record<string, unknown>, config?: RunConfig): CommandProcess;",
    );
  });

  it("does not include runtime code", () => {
    const schema = parseHelpText("my-tool", SAMPLE_HELP);
    const dts = generateTypes(schema);

    expect(dts).not.toContain("const run");
    expect(dts).not.toContain("const toArgs");
    expect(dts).not.toContain("const BINARY");
    expect(dts).not.toContain("spawn(");
  });
});
