import type { CliSchema, ParsedFlag } from "../parse-help-text.js";
import { kebabToCamel } from "../utils/kebab-to-camel.js";

export interface EmitInput {
  binaryName: string;
  schema: CliSchema | null;
  error: string | null;
}

const escapeStringLiteral = (value: string): string => `"${value.replace(/["\\]/g, "\\$&")}"`;

const propertyKey = (name: string): string => {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) return name;
  return escapeStringLiteral(name);
};

const flagTypeString = (flag: ParsedFlag): string => {
  if (!flag.takesValue) return "boolean";
  if (flag.choices && flag.choices.length > 0) {
    return flag.choices.map(escapeStringLiteral).join(" | ");
  }
  return "string";
};

const emitOptionsInline = (flags: ParsedFlag[]): string => {
  if (flags.length === 0) return "Record<string, unknown>";
  const properties = flags.map((flag) => {
    const propertyName = kebabToCamel(flag.longName);
    const optionalMarker = flag.isRequired ? "" : "?";
    return `${propertyKey(propertyName)}${optionalMarker}: ${flagTypeString(flag)}`;
  });
  return `{ ${properties.join("; ")} }`;
};

const emitSubcommandMap = (schema: CliSchema): string => {
  if (schema.command.subcommands.length === 0) return "{}";
  const entries = schema.command.subcommands.map((subcommand) => {
    const optionsType = emitOptionsInline(subcommand.flags ?? []);
    return `${propertyKey(subcommand.name)}: ${optionsType}`;
  });
  return `{ ${entries.join("; ")} }`;
};

export const emitAugmentation = (inputs: EmitInput[]): string => {
  const preamble = [
    "// Generated by cli-to-js/plugin — do not edit.",
    "// Refreshes automatically when the editor rescans source files.",
  ];

  const readyInputs = inputs.filter((input) => input.schema !== null);
  if (readyInputs.length === 0) {
    return `${preamble.join("\n")}\nexport {};\n`;
  }

  const mapEntries = readyInputs
    .map((input) => {
      const shape = emitSubcommandMap(input.schema as CliSchema);
      return `    ${propertyKey(input.binaryName)}: ${shape};`;
    })
    .join("\n");

  return `${preamble.join("\n")}
declare module "cli-to-js" {
  interface KnownCliOptions {
${mapEntries}
  }
}
export {};
`;
};
